name: GitHub Classroom Workflow

on:
  workflow_call:
    inputs:
      test_repo:
        required: true
        type: string
    
env:
    test_repo: ${{ inputs.test_repo }}
  
jobs:
  build:
    name: Classroom test
    runs-on: ubuntu-latest
    steps:
      - name: Start
        run: echo "it's grain"
      
      - uses: actions/checkout@v2
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 7.5.1
          
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'corretto'
            java-version: '17'
                
      - name: Clone tests
        run: |
            tree
            sudo git clone https://oauth2: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@${{ env.test_repo }} task_repo
            sudo chmod -R 777 ./task_repo
            cp -R task_repo/. .
            tree 
          
      - name: Gradle Build
        run: gradle build -Dfile.encoding=UTF-8
          
      - name: Gradle Test
        run: gradle test
